sudo: true
language: haskell
dist: xenial

git:
  depth: 5


cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/universum/.stack-work"


matrix:
  include:

  - ghc: 8.0.2
    env: GHCVER='8.0.2' STACK_YAML="$HOME/build/serokell/universum/stack-$GHCVER.yaml"

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$HOME/build/serokell/universum/stack-$GHCVER.yaml"

  - ghc: 8.4.3
    env: GHCVER='8.4.3' STACK_YAML="$HOME/build/serokell/universum/stack-$GHCVER.yaml"

  - ghc: 8.6.5
    env: GHCVER='8.6.5' STACK_YAML="$HOME/build/serokell/universum/stack.yaml"

  - ghc: 8.8.1
    env: GHCVER='8.8.1' STACK_YAML="$HOME/build/serokell/universum/stack-$GHCVER.yaml"

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$HOME/build/serokell/universum/stack-liquid.yaml"


addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc'
    packages:
      - libgmp-dev
      - cabal-install-2.0


before_install:

  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

  # Install Z3 (for Liquid Haskell)
  - if [ "$STACK_YAML" == "$HOME/build/serokell/universum/stack-liquid.yaml" ]; then
      sudo apt-get -q install z3 -y;
    fi

install:

  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version

  - travis_wait 40 stack build --only-dependencies --no-terminal
  - travis_wait 40 stack build --test --bench --haddock --no-run-tests --no-run-benchmarks --no-haddock-deps --no-terminal

  - |
    if [ "$STACK_YAML" == "$HOME/build/serokell/universum/stack-liquid.yaml" ]; then
      stack install liquidhaskell-0.8.2.4
    else
      echo "Skipping 'liquidhaskell' installation"
    fi

script:

  # Verify cross references
  - wget -O - https://github.com/serokell/xrefcheck/releases/download/v0.1.0.0/release.tar.gz | tar xzv && xrefcheck/bin/xrefcheck
  # Run tests
  - travis_wait 40 stack build --test --no-terminal
  # Optionally run liquidhaskell
  - |
    if [ "$STACK_YAML" == "$HOME/build/serokell/universum/stack-liquid.yaml" ]; then
      stack exec -- liquid --totalhaskell src/Universum/Unsafe.hs
      stack exec -- liquid --totalhaskell src/Universum/Nub.hs
    else
      echo "Skipping 'liquidhaskell' running"
    fi

notifications:
  email: false
  slack:
    rooms:
      - serokell:RfJUgurMOLH2S49BEcRsAdVw
    on_success: change
    on_failure: always
